name: GEN_LIVE

on:
  schedule:
    - cron: "36 9,14 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y sed nmap
        # sudo apt-get install -y yt-dlp sed nmap
      
    - name: Run Multitest Script
      run: |
        cd $GITHUB_WORKSPACE/live_test
        bash ./multi_test.sh 1
      
    - name: Update Results
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update results"
        git push
    - name: Mirror the Github repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/mlabalabala
        dst: gitee/mlabalabala
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: "TVResource"
        force_update: true
